# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2025 CERN.
# Copyright (C) 2024 KTH Royal Institute of Technology.
# Copyright (C) 2025 CESNET z.s.p.o.
# Copyright (C) 2025 Graz University of Technology.
#
# Docker-Services-CLI is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

services:
  redis:
    image: redis:${REDIS_VERSION}
    restart: "unless-stopped"
    read_only: true
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:6380:6379"
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: "unless-stopped"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DB}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:3306:3306"
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=${POSTGRESQL_USER}"
      - "POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}"
      - "POSTGRES_DB=${POSTGRESQL_DB}"
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5433:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTICSEARCH_VERSION}
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9201:9200"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9301:9300"
  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=guekxe3mvqieke1!%&ieIADE"
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9201:9200"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9301:9300"
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: "unless-stopped"
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:15673:15672"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:5673:5672"
  minio:
    image: minio/minio:${MINIO_VERSION}
    restart: "unless-stopped"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/default;
      /usr/bin/docker-entrypoint.sh server /data --console-address :9001
      "
    ports:
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9000:9000"
      - "${DOCKER_SERVICES_IP_BIND:-127.0.0.1}:9001:9001"
